<a href="https://colab.research.google.com/github/Gaurav-29-eng/Anudip/blob/main/POPULAR_MOVIES_ANALYSIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving popular-movies.csv to popular-movies (1).csv

1. Load the dataset.

In [4]:
import pandas as pd

df = pd.read_csv("popular-movies.csv")

In [5]:
df.head()

              title  year   revenue     imdb_id  tmdb_id  trakt_id
0           Hoppers  2026  29000000  tt26443616  1327819   1085761
1  Reminders of Him  2026  18000000  tt33714084  1367642   1116720
2         undertone  2026   9300000  tt35892608  1480387   1213506
3          Scream 7  2026   8400000  tt27047903  1159559    934134
4              GOAT  2026   4700000  tt27613895  1297842   1057839

2. Display the first 10 rows.

In [7]:
df.head(10)

,title,year,revenue,imdb_id,tmdb_id,trakt_id
0,Hoppers,2026,29000000,tt26443616,1327819,1085761
1,Reminders of Him,2026,18000000,tt33714084,1367642,1116720
2,undertone,2026,9300000,tt35892608,1480387,1213506
3,Scream 7,2026,8400000,tt27047903,1159559,934134
4,GOAT,2026,4700000,tt27613895,1297842,1057839
5,The Bride!,2026,2100000,tt30851137,1159831,934595
6,Kiki's Delivery Service,1989,1700000,tt0097814,16859,10314
7,"""Wuthering Heights""",2026,1700000,tt32897959,1316092,1077273
8,Teenage Mutant Ninja Turtles II: The Secret of...,1991,1500000,tt0103060,1497,991
9,Crime 101,2026,1100000,tt32430579,1171145,944042

In [6]:
df.tail()

,title,year,revenue,imdb_id,tmdb_id,trakt_id
995,The Bride!,2026,2100000,tt30851137,1159831,934595
996,Kiki's Delivery Service,1989,1700000,tt0097814,16859,10314
997,"""Wuthering Heights""",2026,1700000,tt32897959,1316092,1077273
998,Teenage Mutant Ninja Turtles II: The Secret of...,1991,1500000,tt0103060,1497,991
999,Crime 101,2026,1100000,tt32430579,1171145,944042

3. Display the last 10 rows.

In [8]:
df.tail(10)

,title,year,revenue,imdb_id,tmdb_id,trakt_id
990,Hoppers,2026,29000000,tt26443616,1327819,1085761
991,Reminders of Him,2026,18000000,tt33714084,1367642,1116720
992,undertone,2026,9300000,tt35892608,1480387,1213506
993,Scream 7,2026,8400000,tt27047903,1159559,934134
994,GOAT,2026,4700000,tt27613895,1297842,1057839
995,The Bride!,2026,2100000,tt30851137,1159831,934595
996,Kiki's Delivery Service,1989,1700000,tt0097814,16859,10314
997,"""Wuthering Heights""",2026,1700000,tt32897959,1316092,1077273
998,Teenage Mutant Ninja Turtles II: The Secret of...,1991,1500000,tt0103060,1497,991
999,Crime 101,2026,1100000,tt32430579,1171145,944042

4. Find the number of rows and columns.

In [10]:
df.shape

(1000, 6)

5. Print all column names.

In [9]:
df.columns

Index(['title', 'year', 'revenue', 'imdb_id', 'tmdb_id', 'trakt_id'], dtype='object')

6. Display data types.

In [11]:
df.dtypes

title       object
year         int64
revenue      int64
imdb_id     object
tmdb_id      int64
trakt_id     int64
dtype: object

7. Display dataset information.

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     1000 non-null   object
 1   year      1000 non-null   int64
 2   revenue   1000 non-null   int64
 3   imdb_id   1000 non-null   object
 4   tmdb_id   1000 non-null   int64
 5   trakt_id  1000 non-null   int64
dtypes: int64(4), object(2)
memory usage: 47.0+ KB

8. Generate descriptive statistics.

In [14]:
df.describe()

              year       revenue       tmdb_id      trakt_id
count  1000.000000  1.000000e+03  1.000000e+03  1.000000e+03
mean   2018.800000  7.750000e+06  1.029867e+06  8.375175e+05
std      14.414152  8.705877e+06  5.195836e+05  4.246083e+05
min    1989.000000  1.100000e+06  1.497000e+03  9.910000e+02
25%    2026.000000  1.700000e+06  1.159559e+06  9.341340e+05
50%    2026.000000  3.400000e+06  1.234494e+06  1.000940e+06
75%    2026.000000  9.300000e+06  1.327819e+06  1.085761e+06
max    2026.000000  2.900000e+07  1.480387e+06  1.213506e+06

In [15]:
df.sample()

        title  year  revenue     imdb_id  tmdb_id  trakt_id
243  Scream 7  2026  8400000  tt27047903  1159559    934134

In [16]:
df.sample(6)

,title,year,revenue,imdb_id,tmdb_id,trakt_id
513,Scream 7,2026,8400000,tt27047903,1159559,934134
548,Teenage Mutant Ninja Turtles II: The Secret of...,1991,1500000,tt0103060,1497,991
235,The Bride!,2026,2100000,tt30851137,1159831,934595
325,The Bride!,2026,2100000,tt30851137,1159831,934595
220,Hoppers,2026,29000000,tt26443616,1327819,1085761
193,Scream 7,2026,8400000,tt27047903,1159559,934134

In [17]:
df.isnull()

     title   year  revenue  imdb_id  tmdb_id  trakt_id
0    False  False    False    False    False     False
1    False  False    False    False    False     False
2    False  False    False    False    False     False
3    False  False    False    False    False     False
4    False  False    False    False    False     False
..     ...    ...      ...      ...      ...       ...
995  False  False    False    False    False     False
996  False  False    False    False    False     False
997  False  False    False    False    False     False
998  False  False    False    False    False     False
999  False  False    False    False    False     False

[1000 rows x 6 columns]

In [20]:
df.isnull().sum()

title       0
year        0
revenue     0
imdb_id     0
tmdb_id     0
trakt_id    0
dtype: int64

In [18]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995     True
996     True
997     True
998     True
999     True
Length: 1000, dtype: bool

In [19]:
df.duplicated().sum()

np.int64(990)

In [21]:
df["title"].unique()

array(['Hoppers', 'Reminders of Him', 'undertone', 'Scream 7', 'GOAT',
       'The Bride!', "Kiki's Delivery Service", '"Wuthering Heights"',
       'Teenage Mutant Ninja Turtles II: The Secret of the Ooze',
       'Crime 101'], dtype=object)

In [22]:
df["title"].nunique()

10

In [23]:
df["year"].value_counts()

year
2026    800
1989    100
1991    100
Name: count, dtype: int64

In [24]:
df["revenue"]

0      29000000
1      18000000
2       9300000
3       8400000
4       4700000
         ...
995     2100000
996     1700000
997     1700000
998     1500000
999     1100000
Name: revenue, Length: 1000, dtype: int64

In [27]:
df[["title","revenue"]]

                                                 title   revenue
0                                              Hoppers  29000000
1                                     Reminders of Him  18000000
2                                            undertone   9300000
3                                             Scream 7   8400000
4                                                 GOAT   4700000
..                                                 ...       ...
995                                         The Bride!   2100000
996                            Kiki's Delivery Service   1700000
997                                "Wuthering Heights"   1700000
998  Teenage Mutant Ninja Turtles II: The Secret of...   1500000
999                                          Crime 101   1100000

[1000 rows x 2 columns]

In [28]:
df[df["revenue"] > 1100000]

,title,year,revenue,imdb_id,tmdb_id,trakt_id
0,Hoppers,2026,29000000,tt26443616,1327819,1085761
1,Reminders of Him,2026,18000000,tt33714084,1367642,1116720
2,undertone,2026,9300000,tt35892608,1480387,1213506
3,Scream 7,2026,8400000,tt27047903,1159559,934134
4,GOAT,2026,4700000,tt27613895,1297842,1057839
...,...,...,...,...,...,...
994,GOAT,2026,4700000,tt27613895,1297842,1057839
995,The Bride!,2026,2100000,tt30851137,1159831,934595
996,Kiki's Delivery Service,1989,1700000,tt0097814,16859,10314
997,"""Wuthering Heights""",2026,1700000,tt32897959,1316092,1077273
998,Teenage Mutant Ninja Turtles II: The Secret of...,1991,1500000,tt0103060,1497,991

In [33]:
df["imdb_id"].max()

'tt35892608'

In [34]:
df["tmdb_id"].min()

1497

In [31]:
df["revenue"].median()

3400000.0

In [35]:
df["trakt_id"].mean()

np.float64(837517.5)

In [37]:
df.sort_values(by="revenue")

         title  year   revenue     imdb_id  tmdb_id  trakt_id
999  Crime 101  2026   1100000  tt32430579  1171145    944042
19   Crime 101  2026   1100000  tt32430579  1171145    944042
969  Crime 101  2026   1100000  tt32430579  1171145    944042
29   Crime 101  2026   1100000  tt32430579  1171145    944042
939  Crime 101  2026   1100000  tt32430579  1171145    944042
..         ...   ...       ...         ...      ...       ...
10     Hoppers  2026  29000000  tt26443616  1327819   1085761
930    Hoppers  2026  29000000  tt26443616  1327819   1085761
240    Hoppers  2026  29000000  tt26443616  1327819   1085761
0      Hoppers  2026  29000000  tt26443616  1327819   1085761
210    Hoppers  2026  29000000  tt26443616  1327819   1085761

[1000 rows x 6 columns]

In [38]:
df.sort_values(by="revenue",ascending=False)

         title  year   revenue     imdb_id  tmdb_id  trakt_id
970    Hoppers  2026  29000000  tt26443616  1327819   1085761
960    Hoppers  2026  29000000  tt26443616  1327819   1085761
20     Hoppers  2026  29000000  tt26443616  1327819   1085761
30     Hoppers  2026  29000000  tt26443616  1327819   1085761
930    Hoppers  2026  29000000  tt26443616  1327819   1085761
..         ...   ...       ...         ...      ...       ...
519  Crime 101  2026   1100000  tt32430579  1171145    944042
509  Crime 101  2026   1100000  tt32430579  1171145    944042
129  Crime 101  2026   1100000  tt32430579  1171145    944042
949  Crime 101  2026   1100000  tt32430579  1171145    944042
959  Crime 101  2026   1100000  tt32430579  1171145    944042

[1000 rows x 6 columns]