<a href="https://colab.research.google.com/github/Gaurav-29-eng/Anudip/blob/main/STUDENT_PERFORMANCE_ANALYSIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving student.csv to student.csv

In [2]:
import pandas as pd

df = pd.read_csv("student.csv")

In [3]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [4]:
df.head(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,6,12,12,13
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,13,12,13
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,2,10,13,13
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,15,16,17
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,12,12,13

In [5]:
df.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [6]:
df.tail(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
639,MS,M,19,R,GT3,T,1,1,other,services,...,4,3,2,1,3,5,0,5,8,0
640,MS,M,18,R,GT3,T,4,2,other,other,...,5,4,3,4,3,3,0,7,7,0
641,MS,F,18,R,GT3,T,2,2,at_home,other,...,5,3,3,1,3,4,0,14,17,15
642,MS,F,17,U,GT3,T,4,3,teacher,other,...,5,5,4,1,1,1,0,6,9,11
643,MS,F,18,R,GT3,T,4,4,teacher,at_home,...,4,4,3,2,2,5,4,7,9,10
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [7]:
df.shape

(649, 33)

In [8]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [9]:
df.dtypes

school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64
 7   Fedu        649 non-null    int64
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64
 13  studytime   649 non-null    int64
 14  failures    649 non-null    int64
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher      649 non-null    object
 21  internet    649 non-null    object
 22  romantic    649 non-null    object
 23  famrel      649 non-null    int64
 24  freetime    649 non-null    int64
 25  goout       649 non-null    int64
 26  Dalc        649 non-null    int64
 27  Walc        649 non-null    int64
 28  health      649 non-null    int64
 29  absences    649 non-null    int64
 30  G1          649 non-null    int64
 31  G2          649 non-null    int64
 32  G3          649 non-null    int64
dtypes: int64(16), object(17)
memory usage: 167.4+ KB

In [11]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000
mean,16.744222,2.514638,2.306626,1.568567,1.930663,0.221880,3.930663,3.180277,3.184900,1.502311,2.280431,3.536210,3.659476,11.399076,11.570108,11.906009
std,1.218138,1.134552,1.099931,0.748660,0.829510,0.593235,0.955717,1.051093,1.175766,0.924834,1.284380,1.446259,4.640759,2.745265,2.913639,3.230656
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,16.000000,2.000000,1.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,2.000000,0.000000,10.000000,10.000000,10.000000
50%,17.000000,2.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,2.000000,11.000000,11.000000,12.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,6.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,32.000000,19.000000,19.000000,19.000000

In [12]:
df.sample()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
235,GP,F,17,U,GT3,T,1,1,at_home,other,...,4,3,4,1,1,5,12,12,12,12

In [13]:
df.sample(15)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
68,GP,F,15,R,LE3,T,2,2,health,services,...,4,1,3,1,3,4,0,11,10,11
510,MS,F,17,R,GT3,T,2,2,other,other,...,5,3,2,1,1,1,0,15,17,17
188,GP,F,16,U,LE3,T,3,3,other,other,...,4,4,5,1,1,4,0,14,14,15
630,MS,F,18,R,LE3,T,4,4,other,other,...,5,4,4,1,1,1,0,15,17,17
171,GP,M,16,R,GT3,T,2,2,at_home,other,...,4,2,2,1,2,3,4,12,10,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
401,GP,M,18,U,GT3,T,4,3,teacher,other,...,5,4,5,2,3,5,0,14,13,14
223,GP,F,17,R,GT3,T,4,3,teacher,other,...,4,4,2,1,1,4,0,11,12,12
385,GP,F,18,U,GT3,T,2,2,at_home,other,...,4,2,5,1,1,2,2,10,9,10
224,GP,F,19,U,GT3,T,3,3,other,other,...,4,3,3,1,2,3,4,12,12,12
488,MS,F,19,U,GT3,T,1,1,at_home,services,...,5,3,1,1,1,3,6,7,9,9
175,GP,M,17,R,GT3,T,3,2,other,other,...,4,4,4,1,4,3,4,7,6,8
480,MS,F,19,U,GT3,T,2,3,at_home,services,...,4,4,4,1,1,2,0,9,9,10
110,GP,M,15,U,LE3,A,4,4,teacher,teacher,...,5,5,3,1,1,4,4,13,14,14
375,GP,F,17,U,LE3,T,0,2,at_home,at_home,...,3,3,3,2,3,2,0,14,14,15

In [14]:
df.isnull()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
645,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
646,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
647,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
648,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [15]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
644    False
645    False
646    False
647    False
648    False
Length: 649, dtype: bool

In [16]:
df.duplicated().sum()

np.int64(0)

Unique values

In [17]:
df["school"].unique()

array(['GP', 'MS'], dtype=object)

Number of unique values

In [18]:
df["school"].nunique()

2

Count frequency.

In [19]:
df["sex"].value_counts()

sex
F    383
M    266
Name: count, dtype: int64

Selecting columns

In [20]:
df["age"]

0      18
1      17
2      15
3      15
4      16
       ..
644    19
645    18
646    18
647    17
648    18
Name: age, Length: 649, dtype: int64

Selecting multiple columns

In [21]:
df[["age", "G3"]]

     age  G3
0     18  11
1     17  11
2     15  12
3     15  14
4     16  13
..   ...  ..
644   19  10
645   18  16
646   18   9
647   17  10
648   18  11

[649 rows x 2 columns]

FILERING DATA

Students with age > 18:

In [22]:
df[df["age"] > 18]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
127,GP,F,19,U,GT3,T,0,1,at_home,other,...,3,4,2,1,1,5,0,9,10,11
166,GP,M,19,U,GT3,T,3,2,services,at_home,...,4,5,4,1,1,4,6,11,9,11
224,GP,F,19,U,GT3,T,3,3,other,other,...,4,3,3,1,2,3,4,12,12,12
279,GP,M,22,U,GT3,T,3,1,services,services,...,5,4,5,5,5,1,12,7,8,5
290,GP,F,19,U,GT3,T,2,2,services,services,...,4,3,3,1,1,5,0,10,10,11
295,GP,M,19,U,LE3,A,4,3,services,at_home,...,4,3,1,1,1,1,4,11,13,14
299,GP,F,20,R,GT3,T,2,1,other,other,...,1,2,3,1,2,2,8,10,12,12
311,GP,F,19,U,GT3,T,3,3,other,services,...,4,3,5,3,3,5,16,11,12,12
322,GP,F,19,R,GT3,T,3,2,services,services,...,3,3,3,4,3,3,0,9,8,10
341,GP,F,19,U,GT3,T,4,4,health,other,...,2,3,4,2,3,2,2,14,13,13
350,GP,M,19,R,LE3,T,2,1,at_home,services,...,4,3,1,1,1,5,0,9,10,11
351,GP,M,20,U,GT3,A,3,2,services,other,...,5,5,3,1,1,5,0,14,15,15
352,GP,M,19,R,GT3,T,3,3,other,services,...,4,5,3,1,2,5,0,10,10,11
361,GP,M,19,U,GT3,T,4,2,health,other,...,5,4,4,1,1,1,9,11,10,10
369,GP,F,19,U,GT3,T,1,1,other,other,...,1,5,5,4,3,5,12,10,10,11
370,GP,F,19,U,LE3,A,1,1,other,other,...,5,3,4,1,1,4,2,8,8,9
384,GP,M,19,R,GT3,T,3,2,at_home,services,...,5,3,4,2,2,5,0,11,10,10
405,GP,F,19,U,LE3,A,2,3,at_home,other,...,2,2,3,3,4,5,16,10,11,11
407,GP,F,21,U,LE3,T,4,4,other,other,...,3,3,2,1,1,5,0,9,12,12
413,GP,M,21,R,LE3,T,1,1,at_home,other,...,5,3,3,5,2,4,21,9,10,10
414,GP,F,20,R,GT3,T,1,1,other,other,...,3,2,2,1,3,3,8,11,15,15
415,GP,F,19,U,GT3,T,4,4,teacher,other,...,3,2,5,4,4,5,5,9,10,11
419,GP,M,19,U,GT3,T,2,1,other,other,...,5,3,4,1,4,4,10,7,11,11
421,GP,F,20,U,GT3,T,1,0,other,other,...,5,3,1,1,1,5,5,8,10,10
480,MS,F,19,U,GT3,T,2,3,at_home,services,...,4,4,4,1,1,2,0,9,9,10
488,MS,F,19,U,GT3,T,1,1,at_home,services,...,5,3,1,1,1,3,6,7,9,9
491,MS,F,19,U,GT3,T,1,1,other,other,...,1,1,4,4,1,1,12,7,8,9
504,MS,F,19,U,LE3,T,2,2,other,other,...,5,4,5,1,1,1,0,12,13,13
506,MS,F,20,U,GT3,T,3,3,at_home,services,...,3,3,4,2,4,3,8,11,9,10
552,MS,M,19,U,GT3,T,1,1,other,other,...,4,4,3,3,4,4,2,9,9,10
568,MS,M,19,U,GT3,T,3,2,at_home,services,...,3,2,1,1,1,3,4,6,11,9
571,MS,M,19,U,GT3,T,2,1,at_home,other,...,4,4,3,1,3,5,4,8,9,9
574,MS,M,20,R,GT3,T,1,1,other,other,...,4,4,3,2,4,4,12,8,11,10
577,MS,M,19,R,GT3,T,1,1,other,services,...,5,4,4,3,3,2,8,10,9,11
580,MS,M,19,R,GT3,T,1,1,other,other,...,4,4,4,3,3,5,4,8,9,10
582,MS,F,19,U,LE3,A,1,1,at_home,other,...,1,4,4,1,1,5,0,6,8,7
605,MS,F,19,U,GT3,T,1,1,at_home,services,...,5,5,5,2,3,2,0,5,0,0
610,MS,F,19,R,GT3,A,1,1,at_home,at_home,...,3,5,4,1,4,1,0,8,0,0
632,MS,F,19,R,GT3,T,1,1,at_home,other,...,4,3,3,1,1,3,4,7,8,9
639,MS,M,19,R,GT3,T,1,1,other,services,...,4,3,2,1,3,5,0,5,8,0
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10

Students scoring above 15:

In [23]:
df[df["G3"] > 15]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,15,16,17
15,GP,F,16,U,GT3,T,4,4,health,other,...,4,4,4,1,2,2,6,17,17,17
47,GP,M,16,U,GT3,T,4,3,health,services,...,4,2,2,1,1,2,2,17,17,17
51,GP,F,15,U,LE3,T,4,2,health,other,...,4,3,3,1,1,5,0,16,14,16
57,GP,M,15,U,GT3,T,4,4,teacher,health,...,3,2,2,1,1,5,8,15,15,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
630,MS,F,18,R,LE3,T,4,4,other,other,...,5,4,4,1,1,1,0,15,17,17
634,MS,F,18,U,GT3,T,3,3,other,other,...,4,1,3,1,2,1,1,16,16,16
636,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,3,2,4,1,4,2,4,17,18,19
638,MS,M,17,U,GT3,T,2,3,other,services,...,4,4,3,1,1,3,4,14,15,16
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16

Highest final marks.

In [24]:
df["G3"].max()

19

Lowest final marks

In [25]:
df["G3"].min()

0

Average marks

In [26]:
df["G3"].mean()

np.float64(11.906009244992296)

Middle Value

In [27]:
df["G3"].median()

12.0

Ascending

In [28]:
df.sort_values(by="G3")

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
603,MS,F,18,R,LE3,A,4,2,teacher,other,...,5,3,1,1,1,5,0,5,0,0
605,MS,F,19,U,GT3,T,1,1,at_home,services,...,5,5,5,2,3,2,0,5,0,0
597,MS,F,18,R,GT3,T,2,2,at_home,other,...,4,3,3,1,1,4,0,9,0,0
610,MS,F,19,R,GT3,A,1,1,at_home,at_home,...,3,5,4,1,4,1,0,8,0,0
626,MS,F,18,R,GT3,T,4,4,other,teacher,...,3,2,2,4,2,5,0,7,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,GP,M,17,R,GT3,T,1,2,at_home,at_home,...,3,5,2,2,2,1,2,16,17,18
416,GP,M,17,U,LE3,A,3,2,other,other,...,4,4,4,1,2,5,10,16,18,18
606,MS,F,17,U,GT3,T,4,2,teacher,other,...,4,2,3,3,1,5,0,18,18,18
338,GP,F,17,R,LE3,T,3,1,services,other,...,3,1,2,1,1,3,0,18,19,19
636,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,3,2,4,1,4,2,4,17,18,19

Descending

In [29]:
df.sort_values(by="G3", ascending=False)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
636,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,3,2,4,1,4,2,4,17,18,19
338,GP,F,17,R,LE3,T,3,1,services,other,...,3,1,2,1,1,3,0,18,19,19
596,MS,F,17,U,GT3,T,4,2,other,other,...,4,3,3,1,2,4,0,17,18,18
113,GP,M,15,U,LE3,T,4,2,teacher,other,...,3,5,2,1,1,3,10,18,17,18
617,MS,F,18,U,LE3,T,1,1,at_home,services,...,5,3,2,1,1,4,0,19,17,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583,MS,F,18,R,GT3,T,2,2,other,other,...,5,5,5,1,1,3,0,8,6,0
610,MS,F,19,R,GT3,A,1,1,at_home,at_home,...,3,5,4,1,4,1,0,8,0,0
605,MS,F,19,U,GT3,T,1,1,at_home,services,...,5,5,5,2,3,2,0,5,0,0
603,MS,F,18,R,LE3,A,4,2,teacher,other,...,5,3,1,1,1,5,0,5,0,0
626,MS,F,18,R,GT3,T,4,4,other,teacher,...,3,2,2,4,2,5,0,7,5,0

Locate value for 10th row

In [30]:
df.loc[10]

school                GP
sex                    F
age                   15
address                U
famsize              GT3
Pstatus                T
Medu                   4
Fedu                   4
Mjob             teacher
Fjob              health
reason        reputation
guardian          mother
traveltime             1
studytime              2
failures               0
schoolsup             no
famsup               yes
paid                  no
activities            no
nursery              yes
higher               yes
internet             yes
romantic              no
famrel                 3
freetime               3
goout                  3
Dalc                   1
Walc                   2
health                 2
absences               2
G1                    14
G2                    14
G3                    14
Name: 10, dtype: object

In [31]:
df.rename(columns={"G3":"Final Marks"})

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,Final Marks
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [32]:
df.rename(columns={"G1":"Unit Test Marks"})

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,Unit Test Marks,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [33]:
df.rename(columns={"G2":"Mid Sem Marks"})

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,Mid Sem Marks,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [39]:
df["Average"]=(df["G1"]+df["G2"]+df["G3"])/3

Above code generated a temporary dataset from the available dataset and has included average column in it and hence head() displays the average column from the new dataset

In [40]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,Average
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,4,0,11,11,7.333333
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,2,9,11,11,10.333333
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,6,12,13,12,12.333333
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,0,14,14,14,14.000000
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,0,11,13,13,12.333333

In [42]:
df["Total Marks"]=(df["G1"]+df["G2"]+df["G3"])

In [43]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,Average,Total Marks
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,1,1,3,4,0,11,11,7.333333,22
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,1,1,3,2,9,11,11,10.333333,31
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,2,2,3,3,6,12,13,12,12.333333,37
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,1,1,5,0,14,14,14,14.000000,42
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,1,2,5,0,11,13,13,12.333333,37

In [46]:
df.drop("Average",axis=1)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,Total Marks
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,4,0,11,11,22
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,2,9,11,11,31
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,6,12,13,12,37
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,0,14,14,14,42
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,0,11,13,13,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,4,2,1,2,5,4,10,11,10,31
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,3,4,1,1,1,4,15,15,16,46
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,5,6,11,12,9,32
647,MS,M,17,U,LE3,T,3,1,services,services,...,4,5,3,4,2,6,10,10,10,30
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,1,3,4,5,4,10,11,11,32

DELETE DUPLICATES.

In [48]:
df.drop_duplicates()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,Average,Total Marks
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,1,1,3,4,0,11,11,7.333333,22
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,1,1,3,2,9,11,11,10.333333,31
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,2,2,3,3,6,12,13,12,12.333333,37
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,1,1,5,0,14,14,14,14.000000,42
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,1,2,5,0,11,13,13,12.333333,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,2,1,2,5,4,10,11,10,10.333333,31
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,1,1,1,4,15,15,16,15.333333,46
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,5,6,11,12,9,10.666667,32
647,MS,M,17,U,LE3,T,3,1,services,services,...,5,3,4,2,6,10,10,10,10.000000,30
648,MS,M,18,R,LE3,T,3,2,services,other,...,1,3,4,5,4,10,11,11,10.666667,32

In [50]:
df.isnull().sum()

school         0
sex            0
age            0
address        0
famsize        0
Pstatus        0
Medu           0
Fedu           0
Mjob           0
Fjob           0
reason         0
guardian       0
traveltime     0
studytime      0
failures       0
schoolsup      0
famsup         0
paid           0
activities     0
nursery        0
higher         0
internet       0
romantic       0
famrel         0
freetime       0
goout          0
Dalc           0
Walc           0
health         0
absences       0
G1             0
G2             0
G3             0
Average        0
Total Marks    0
dtype: int64

Remove Null Values

In [51]:
df.dropna()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,Average,Total Marks
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,1,1,3,4,0,11,11,7.333333,22
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,1,1,3,2,9,11,11,10.333333,31
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,2,2,3,3,6,12,13,12,12.333333,37
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,1,1,5,0,14,14,14,14.000000,42
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,1,2,5,0,11,13,13,12.333333,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,2,1,2,5,4,10,11,10,10.333333,31
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,1,1,1,4,15,15,16,15.333333,46
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,5,6,11,12,9,10.666667,32
647,MS,M,17,U,LE3,T,3,1,services,services,...,5,3,4,2,6,10,10,10,10.000000,30
648,MS,M,18,R,LE3,T,3,2,services,other,...,1,3,4,5,4,10,11,11,10.666667,32

Replace null values with 0

In [53]:
df.fillna(0)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,Average,Total Marks
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,1,1,3,4,0,11,11,7.333333,22
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,1,1,3,2,9,11,11,10.333333,31
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,2,2,3,3,6,12,13,12,12.333333,37
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,1,1,5,0,14,14,14,14.000000,42
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,1,2,5,0,11,13,13,12.333333,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,2,1,2,5,4,10,11,10,10.333333,31
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,1,1,1,4,15,15,16,15.333333,46
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,5,6,11,12,9,10.666667,32
647,MS,M,17,U,LE3,T,3,1,services,services,...,5,3,4,2,6,10,10,10,10.000000,30
648,MS,M,18,R,LE3,T,3,2,services,other,...,1,3,4,5,4,10,11,11,10.666667,32

FIND THE STUDENTS WHO STUDY MORE THAN 3 HOURS.

In [59]:
studytime = df[df["studytime"] > 3]
studytime

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,Average,Total Marks
47,GP,M,16,U,GT3,T,4,3,health,services,...,2,1,1,2,2,17,17,17,17.000000,51
66,GP,M,15,U,GT3,A,4,4,other,services,...,3,5,5,3,0,11,12,12,11.666667,35
67,GP,F,16,U,GT3,T,3,1,services,other,...,3,1,2,5,0,10,9,10,9.666667,29
69,GP,F,15,R,LE3,T,3,1,other,other,...,2,2,3,3,6,15,15,15,15.000000,45
70,GP,M,16,U,GT3,T,3,1,other,other,...,2,1,1,5,2,13,11,11,11.666667,35
71,GP,M,15,U,GT3,T,4,2,other,other,...,3,1,1,3,0,11,9,10,10.000000,30
76,GP,M,15,U,GT3,T,4,0,teacher,other,...,3,1,1,1,0,12,11,11,11.333333,34
77,GP,F,16,U,GT3,T,2,2,other,other,...,3,1,3,3,1,13,13,13,13.000000,39
94,GP,M,15,U,LE3,T,2,2,services,health,...,4,1,1,4,2,11,12,12,11.666667,35
95,GP,F,15,R,GT3,T,1,1,at_home,other,...,2,1,1,1,4,13,13,13,13.000000,39
105,GP,F,15,U,GT3,A,3,3,other,health,...,3,1,1,4,10,10,10,10,10.000000,30
106,GP,F,15,U,GT3,T,2,2,other,other,...,2,1,1,3,4,10,10,10,10.000000,30
108,GP,M,15,R,GT3,T,4,4,other,other,...,5,3,5,1,8,12,10,11,11.000000,33
121,GP,M,15,U,GT3,T,2,2,services,services,...,4,1,2,5,6,14,13,13,13.333333,40
149,GP,M,15,U,GT3,T,4,3,teacher,services,...,2,1,1,3,6,9,11,11,10.333333,31
218,GP,F,16,R,GT3,T,2,2,services,services,...,5,1,1,5,6,13,13,13,13.000000,39
224,GP,F,19,U,GT3,T,3,3,other,other,...,3,1,2,3,4,12,12,12,12.000000,36
289,GP,F,17,U,LE3,T,4,2,teacher,services,...,3,1,1,4,2,14,15,17,15.333333,46
298,GP,F,17,U,LE3,T,2,2,services,services,...,1,1,1,2,2,10,11,12,11.000000,33
312,GP,F,18,U,GT3,T,2,3,other,services,...,5,1,3,2,10,16,16,16,16.000000,48
327,GP,F,18,R,LE3,T,1,1,at_home,other,...,2,1,1,3,2,17,17,18,17.333333,52
338,GP,F,17,R,LE3,T,3,1,services,other,...,2,1,1,3,0,18,19,19,18.666667,56
343,GP,F,18,U,GT3,T,4,3,other,other,...,3,1,1,3,0,16,17,17,16.666667,50
349,GP,F,17,U,GT3,T,3,2,health,health,...,2,1,2,5,0,18,18,18,18.000000,54
383,GP,M,18,U,LE3,T,2,2,other,other,...,5,2,4,5,0,11,11,12,11.333333,34
390,GP,F,18,R,GT3,T,2,2,at_home,other,...,4,1,1,4,6,14,13,14,13.666667,41
393,GP,F,18,U,LE3,T,3,3,services,services,...,3,1,1,1,4,14,14,15,14.333333,43
434,MS,F,16,U,LE3,A,2,2,at_home,other,...,1,1,1,1,4,10,9,11,10.000000,30
458,MS,F,16,R,GT3,T,1,1,other,other,...,2,1,1,1,0,13,10,13,12.000000,36
497,MS,M,17,U,GT3,T,3,3,services,at_home,...,5,3,4,5,0,10,11,10,10.333333,31
502,MS,M,17,R,LE3,T,2,2,services,services,...,5,3,5,3,2,10,8,9,9.000000,27
503,MS,F,16,U,GT3,T,1,1,other,other,...,1,1,1,5,0,14,14,14,14.000000,42
523,MS,M,18,U,LE3,T,4,4,at_home,health,...,5,5,5,5,2,5,6,6,5.666667,17
536,MS,M,15,U,LE3,A,2,2,other,other,...,5,2,3,5,8,13,14,14,13.666667,41
606,MS,F,17,U,GT3,T,4,2,teacher,other,...,3,3,1,5,0,18,18,18,18.000000,54

FIND THE STUDENTS WITH INTERNET

In [60]:
internet = df[df["internet"] == "yes"]
internet

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,Average,Total Marks
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,1,1,3,2,9,11,11,10.333333,31
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,2,2,3,3,6,12,13,12,12.333333,37
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,1,1,5,0,14,14,14,14.000000,42
5,GP,M,16,U,LE3,T,4,3,services,other,...,2,1,2,5,6,12,12,13,12.333333,37
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,1,1,3,0,13,12,13,12.666667,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643,MS,F,18,R,GT3,T,4,4,teacher,at_home,...,3,2,2,5,4,7,9,10,8.666667,26
644,MS,F,19,R,GT3,T,2,3,services,other,...,2,1,2,5,4,10,11,10,10.333333,31
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,1,1,1,4,15,15,16,15.333333,46
647,MS,M,17,U,LE3,T,3,1,services,services,...,5,3,4,2,6,10,10,10,10.000000,30
648,MS,M,18,R,LE3,T,3,2,services,other,...,1,3,4,5,4,10,11,11,10.666667,32

FIND THE STUDENTS WITHOUT INTERNET

In [62]:
nointernet = df[df["internet"] == "no"]
nointernet

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,Average,Total Marks
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,1,1,3,4,0,11,11,7.333333,22
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,1,2,5,0,11,13,13,12.333333,37
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,1,1,2,10,13,13,12.000000,36
17,GP,F,16,U,GT3,T,3,3,other,other,...,2,1,1,4,2,13,14,14,13.666667,41
35,GP,F,15,U,GT3,T,2,3,other,other,...,1,1,1,5,4,11,11,11,11.000000,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628,MS,F,17,U,GT3,T,2,2,other,at_home,...,3,1,1,3,8,10,11,12,11.000000,33
639,MS,M,19,R,GT3,T,1,1,other,services,...,2,1,3,5,0,5,8,0,4.333333,13
640,MS,M,18,R,GT3,T,4,2,other,other,...,3,4,3,3,0,7,7,0,4.666667,14
641,MS,F,18,R,GT3,T,2,2,at_home,other,...,3,1,3,4,0,14,17,15,15.333333,46
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,5,6,11,12,9,10.666667,32

FIND THE STUDENTS WHOSE ATTENDANCE IS POOR (>10)

In [69]:
attendance = df[df["absences"] < 10]
attendance

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,Average,Total Marks
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,1,1,3,4,0,11,11,7.333333,22
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,1,1,3,2,9,11,11,10.333333,31
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,2,2,3,3,6,12,13,12,12.333333,37
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,1,1,5,0,14,14,14,14.000000,42
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,1,2,5,0,11,13,13,12.333333,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,2,1,2,5,4,10,11,10,10.333333,31
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,1,1,1,4,15,15,16,15.333333,46
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,5,6,11,12,9,10.666667,32
647,MS,M,17,U,LE3,T,3,1,services,services,...,5,3,4,2,6,10,10,10,10.000000,30
648,MS,M,18,R,LE3,T,3,2,services,other,...,1,3,4,5,4,10,11,11,10.666667,32

FIND THE TOP 3 STUDENTS

In [63]:
top3 = df.nlargest(3, "G3")
top3

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,Average,Total Marks
338,GP,F,17,R,LE3,T,3,1,services,other,...,2,1,1,3,0,18,19,19,18.666667,56
636,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,4,1,4,2,4,17,18,19,18.000000,54
113,GP,M,15,U,LE3,T,4,2,teacher,other,...,2,1,1,3,10,18,17,18,17.666667,53

FIND THE BOTTOM 3 STUDENTS

In [64]:
bottom3 = df.nsmallest(3, "G3")
bottom3

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,Average,Total Marks
163,GP,M,18,U,LE3,T,1,1,other,other,...,5,2,5,4,0,11,9,0,6.666667,20
440,MS,M,16,U,GT3,T,1,1,at_home,services,...,5,4,5,3,0,7,0,0,2.333333,7
519,MS,M,16,R,GT3,T,2,1,other,services,...,1,1,1,2,0,8,7,0,5.000000,15

Find the students who go out frequently

In [70]:
goout = df[df["goout"] >= 4]
goout

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,Average,Total Marks
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,1,1,3,4,0,11,11,7.333333,22
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,1,1,3,0,13,12,13,12.666667,38
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,1,1,2,10,13,13,12.000000,36
15,GP,F,16,U,GT3,T,4,4,health,other,...,4,1,2,2,6,17,17,17,17.000000,51
18,GP,M,17,U,GT3,T,3,2,services,services,...,5,2,4,5,2,8,8,7,7.666667,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,MS,F,17,R,GT3,T,3,1,at_home,other,...,4,2,3,1,10,8,9,9,8.666667,26
636,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,4,1,4,2,4,17,18,19,18.000000,54
642,MS,F,17,U,GT3,T,4,3,teacher,other,...,4,1,1,1,0,6,9,11,8.666667,26
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,1,1,1,4,15,15,16,15.333333,46
647,MS,M,17,U,LE3,T,3,1,services,services,...,5,3,4,2,6,10,10,10,10.000000,30